auth:
  jwt:
    issuer: akerkesilaaaaaaaaaaaaaaaaaaaaaaa
    secret: qwwqwdfnrivbincvutbewfinvfirbwnrifrwbnfonwiovfnwrionvwinvubnvwifjwiojfoewjfienviwnnwrnvkrwnkvnmweodfeqffkowqemfineinfnceqncenkcnkenckenkncdknckdnckdokepfkoekfoejmeknmfkqnmwflmqkenf


spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/sas_auth
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: auth-service
    root-url: ${server.schema}:${server.host}:${server.port}${server.servlet.context-path}

server:
  schema: http
  host: localhost
  port: 3000
  servlet:
    context-path: /api/v1/auth/
