spring:
  application:
    name: notification-service
  graphql:
    graphiql:
      enabled: true

  telegram:
    bot:
      username: salonsystembot
      token: 6659190171:AAG5V_m00IZwkuVw63oVXYUA1XlhM4mtdAU
  datasource:
    url: jdbc:postgresql://localhost:5432/salon