CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_time       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_time TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255),
    surname            VARCHAR(255),
    phone              VARCHAR(255),
    email              VARCHAR(255),
    email_verified     BOOLEAN,
    password           VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE role
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_time       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_time TIMESTAMP WITHOUT TIME ZONE,
    role               VARCHAR(255),
    user_id            BIGINT,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

ALTER TABLE role
    ADD CONSTRAINT FK_ROLE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE TABLE permission
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_time       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_time TIMESTAMP WITHOUT TIME ZONE,
    type               VARCHAR(255),
    target             BIGINT,
    role_id            BIGINT,
    CONSTRAINT pk_permission PRIMARY KEY (id)
);

ALTER TABLE permission
    ADD CONSTRAINT FK_PERMISSION_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);