qr:
  charset: UTF-8
spring:
  application:
    name: qr-service
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA}
server:
  port: 9999
  servlet:
    context-path: /api/v1/qr/