qr:
  charset: UTF-8
spring:
  cloud:
    openfeign:
      client:
        config:
          storage-service:
            url: http://localhost:8080/storage/
  application:
    name: qr-service
eureka:
  client:
    service-url:
      defaultZone: https://server-akerke.fibo.cloud:8761/eureka
    enabled: false
server:
  port: 9999
  servlet:
    context-path: /api/v1/qr/
