version: '3'
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9090'
    command: minio server /data
volumes:
  minio_storage: {}
