global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'mail_sender'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mail-sender:4000']
        labels:
          application: 'Mail Sender Application'
