global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'mail_sender'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mail-sender:1000']
        labels:
          application: 'Mail Sender Application'
  - job_name: 'auth-server'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['auth-server:4000']
        labels:
          application: 'Auth server Application'
  - job_name: 'qr-service'
    metrics_path: 'api/v1/qr/actuator/prometheus'
    static_configs:
      - targets: ['qr-service:8004']
        labels:
          application: 'Qr service Application'
  - job_name: 'chat-service'
    metrics_path: 'api/v1/chat/actuator/prometheus'
    static_configs:
      - targets: ['chat-service:8001']
        labels:
          application: 'chat service Application'
  - job_name: 'storage-service'
    metrics_path: 'api/v1/storage/actuator/prometheus'
    static_configs:
      - targets: ['storage-service:8005']
        labels:
          application: 'storage service Application'
  - job_name: 'salon-service'
    metrics_path: 'api/v1/storage/actuator/prometheus'
    static_configs:
      - targets: [ 'salon-service:8005' ]
        labels:
          application: 'salon service Application'