spring:
  thread-executor: virtual
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
  application:
    name: course-service
  minio:
    download-link: ${server.protocol:http}://${server.host:localhost}:${server.port:8080}
    endpoint: http://127.0.0.1:9000
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
