apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
spec:
  selector:
    matchLabels:
      app: discovery
  replicas: 1
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - name: discovery
          image: rnbsrva/discovery
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discovery
spec:
  selector:
    app: discovery
  ports:
    - protocol: "TCP"
      port: 8761
      targetPort: 8761
  type: LoadBalancer

