name: CI CD Salon appointment system

on:
  push:
    branches: [main]
    paths:
      - 'api-gateway/**'
      - 'chat-service/**'
      - 'auth-service/**'
      - 'mail-sender/**'
      - 'discovery/**'
      - 'notification-service/**'
      - 'qr-service/**'
      - 'salon-service/**'
      - 'storage-service/**'

jobs:
  build:
    name: Trigger build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            api-gateway:
              - 'api-gateway/**'
            chat-service:
              - 'chat-service/**'
            auth-service:
              - 'auth-service/**'
            mail-sender:
              - 'mail-sender/**'
            discovery:
              - 'discovery/**'
            notification-service:
              - 'notification-service/**'
            qr-service:
              - 'qr-service/**'
            salon-service:
              - 'salon-service/**'
            storage-service:
              - 'storage-service/**'

      - name: Check changes for each service
        run: |
          echo "Changed files: ${{ github.event_name }} ${{ github.event.before }}...${{ github.sha }}"
          echo "Changed services: ${{ steps.changes.outputs.services }}"
      - name: Trigger api gateway changes
        if: steps.changes.output.api-gateway == 'true'
        run: |
          cd .github/workflows
          mv api-gateway.yml workflow.yml
          cd ../..
          mv .github/workflows/workflow.yml .github/workflows/api-gateway.yml


        env:
          SERVICES: ${{ steps.changes.outputs.services }}
