name: CI/CD with Jib and Docker Hub

on:
  push:
    paths:
      - "qr-service/**"
      - ".github/workflows/qr-service.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Qr service
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Maven clean install
        run: mvn clean install -f qr-service/pom.xml

      - name: Build Docker Image Qr service
        run: docker build -t rnbsrva/qr-service -f qr-service/Dockerfile qr-service/

      - name: Log in to Docker Hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image Qr service
        run: docker push rnbsrva/qr-service


        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker stop qr-service
            sudo docker rmi -f qr-service
            cd sas
            sudo docker compose up -d